# Generated by Django 2.2 on 2019-12-11 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, verbose_name='STT')),
                ('team', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội')),
                ('ban', models.CharField(blank=True, max_length=50, null=True)),
                ('pick', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Ban - Pick',
                'verbose_name_plural': 'Ban - Pick',
                'db_table': 'd_cs_go_ban_pick',
            },
        ),
        migrations.CreateModel(
            name='BetMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thi đấu')),
                ('team_a', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội A')),
                ('id_team_a', models.IntegerField(blank=True, null=True, verbose_name='ID đội A')),
                ('point_team_a', models.IntegerField(blank=True, null=True, verbose_name='Điểm đội A')),
                ('team_b', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội B')),
                ('id_team_b', models.IntegerField(blank=True, null=True, verbose_name='ID đội B')),
                ('point_team_b', models.IntegerField(blank=True, null=True, verbose_name='Điểm đội B')),
                ('bet_team_a', models.FloatField(blank=True, null=True)),
                ('bet_team_b', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nguồn')),
            ],
            options={
                'verbose_name': 'BET',
                'verbose_name_plural': 'BET',
                'db_table': 'd_cs_go_bet_match',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thi đấu')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Thể thức chơi')),
                ('team_a', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội A')),
                ('id_team_a', models.IntegerField(blank=True, null=True, verbose_name='ID đội A')),
                ('point_team_a', models.IntegerField(blank=True, null=True, verbose_name='Điểm đội A')),
                ('team_b', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội B')),
                ('id_team_b', models.IntegerField(blank=True, null=True, verbose_name='ID đội B')),
                ('point_team_b', models.IntegerField(blank=True, null=True, verbose_name='Điểm đội B')),
                ('source', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nguồn')),
                ('bet_team_a', models.FloatField(blank=True, null=True)),
                ('bet_team_b', models.FloatField(blank=True, null=True)),
                ('source_bet', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nguồn bet')),
            ],
            options={
                'verbose_name': 'Trận đấu',
                'verbose_name_plural': 'Trận đấu',
                'db_table': 'd_cs_go_match',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(blank=True, max_length=200, null=True, verbose_name='Đội')),
                ('id_player', models.IntegerField(blank=True, null=True, verbose_name='ID Người chơi')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người chơi')),
                ('elo', models.FloatField(blank=True, default=1800, null=True)),
            ],
            options={
                'db_table': 'd_cs_go_player',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bản đồ')),
                ('half', models.IntegerField(blank=True, null=True, verbose_name='Hiệp')),
                ('team', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội')),
                ('point', models.IntegerField(blank=True, null=True, verbose_name='Điểm')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bet.Match', verbose_name='Trận đấu')),
            ],
            options={
                'verbose_name': 'Kết quả từng hiệp',
                'verbose_name_plural': 'Kết quả từng hiệp',
                'db_table': 'd_cs_go_result',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bản đồ')),
                ('team', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội')),
                ('player', models.CharField(blank=True, max_length=50, null=True, verbose_name='Người chơi')),
                ('id_player', models.IntegerField(blank=True, null=True, verbose_name='ID Người chơi')),
                ('kill', models.IntegerField(blank=True, null=True)),
                ('death', models.IntegerField(blank=True, null=True)),
                ('adr', models.FloatField(blank=True, null=True)),
                ('kast', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('bet', models.FloatField(blank=True, default=0, null=True)),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bet.Match', verbose_name='Trận đấu')),
            ],
            options={
                'verbose_name': 'Hiệu suất',
                'verbose_name_plural': 'Hiệu suất',
                'db_table': 'd_cs_go_performance',
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['source'], name='d_cs_go_mat_source_bd027f_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['time'], name='d_cs_go_mat_time_78ad42_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['team_a'], name='d_cs_go_mat_team_a_3bc287_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['point_team_a'], name='d_cs_go_mat_point_t_63a882_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['team_b'], name='d_cs_go_mat_team_b_7ed438_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['point_team_b'], name='d_cs_go_mat_point_t_ff4707_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['time'], name='d_cs_go_bet_time_f63a51_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['team_a'], name='d_cs_go_bet_team_a_b83363_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['point_team_a'], name='d_cs_go_bet_point_t_8b5222_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['team_b'], name='d_cs_go_bet_team_b_8b471b_idx'),
        ),
        migrations.AddIndex(
            model_name='betmatch',
            index=models.Index(fields=['point_team_b'], name='d_cs_go_bet_point_t_10501b_idx'),
        ),
        migrations.AddField(
            model_name='banpick',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bet.Match', verbose_name='Trận đấu'),
        ),
    ]
