# Generated by Django 2.2 on 2019-12-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='w_a',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tỷ lệ thắng đội A'),
        ),
        migrations.AddField(
            model_name='performance',
            name='elo',
            field=models.FloatField(blank=True, default=1800, null=True),
        ),
    ]
