# Generated by Django 2.2 on 2019-12-13 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_auto_20191212_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetUpcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banker', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhà cái')),
                ('bet_team_a', models.FloatField(blank=True, null=True)),
                ('bet_team_b', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'BET - Trận đấu sắp diễn ra',
                'verbose_name_plural': 'BET - Trận đấu sắp diễn ra',
                'db_table': 'd_cs_go_bet_upcoming',
            },
        ),
        migrations.CreateModel(
            name='MatchUpcoming',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian thi đấu')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='Thể thức chơi')),
                ('team_a', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội A')),
                ('id_team_a', models.IntegerField(blank=True, null=True, verbose_name='ID đội A')),
                ('team_b', models.CharField(blank=True, max_length=50, null=True, verbose_name='Đội B')),
                ('id_team_b', models.IntegerField(blank=True, null=True, verbose_name='ID đội B')),
                ('source', models.CharField(blank=True, max_length=500, null=True, verbose_name='Nguồn')),
            ],
            options={
                'verbose_name': 'Trận đấu sắp diễn ra',
                'verbose_name_plural': 'Trận đấu sắp diễn ra',
                'db_table': 'd_cs_go_match_upcoming',
            },
        ),
        migrations.AddIndex(
            model_name='matchupcoming',
            index=models.Index(fields=['source'], name='d_cs_go_mat_source_70d5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='matchupcoming',
            index=models.Index(fields=['time'], name='d_cs_go_mat_time_5261f6_idx'),
        ),
        migrations.AddIndex(
            model_name='matchupcoming',
            index=models.Index(fields=['team_a'], name='d_cs_go_mat_team_a_6e0fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='matchupcoming',
            index=models.Index(fields=['team_b'], name='d_cs_go_mat_team_b_37f03a_idx'),
        ),
        migrations.AddField(
            model_name='betupcoming',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bet.MatchUpcoming', verbose_name='Trận đấu'),
        ),
    ]
