# Generated by Django 2.2 on 2019-12-16 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0004_bankroll'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchupcoming',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
